sudo: required
dist: trusty
language: c
compiler: gcc
# XXX tests are disabled for the moment because the travis VM's CPU
# type isn't supported, and because there are odd timeouts with no-op
# tests
script: ./src/script/setup_travis.sh && cmake . && make && make package && ctest
notifications:
  email:
    - pipcet@gmail.com
